inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.2

Naming/MethodParameterName:
  AllowedNames: ["x", "y", "z"]

RSpec/EmptyLineAfterHook:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/ci-helper.rb

Style/HashConversion:
  Exclude:
    - spec/**/*_spec.rb
