name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


env:
  FULL_COVERAGE_CHECK: true

jobs:
  full-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
      - name: Install dependencies
        run: gem install bundler && bundle install
      - name: Build and install gem to systems gems
        run: bundle exec rake install
      - name: Run Linter
        run: ci-helper RubocopLint
      - name: Check missed spec suffixes
        run: ci-helper CheckSpecSuffixes --extra-paths spec/*.rb --ignored-paths spec/*_helper.rb
      - name: Run specs
        run: ci-helper RunSpecs
      - name: Audit
        run: ci-helper BundlerAudit
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  specs:
    runs-on: ubuntu-latest

    env:
      FULL_TEST_COVERAGE_CHECK: false

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run specs
        run: bundle exec rspec
